name: first_workflow

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print 1
        run: echo "hello World 1"

      - name: print 2
        run: echo "hello World 2"
